### ISSUE TITLE
README.md misleading

### ISSUE THREAD

**Issue by almereyda** [valueflows/software-iface#1]
Update with our project ideas.

**Comment by fosterlynn** [comment]
Did minimal update so it is not misleading.  Again, edited and committed in place.

**Comment by almereyda** [comment]
We have moved the ValueFlows GitHub organization to https://lab.allmende.io/valueflows.  This issue has been closed here, and all further discussion on this issue can be done at https://lab.allmende.io/valueflows/software-iface/-/issues/1.  If you have not done so, you are very welcome to register at https://lab.allmende.io/ and join the ValueFlows organization there.
